//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turneringer
    {
        public int TurneringsID { get; set; }
        public string Turneringsnavn { get; set; }
        public Nullable<int> SpillerID { get; set; }
        public string Spillernavn { get; set; }
        public string SpillerTelefonnummer { get; set; }
        public Nullable<int> DommerID { get; set; }
        public string Dommernavn { get; set; }
        public string Dommertelefonnummer { get; set; }
        public Nullable<int> DommerLevel { get; set; }
    
        public virtual Ansatte Ansatte { get; set; }
        public virtual Spillere Spillere { get; set; }
    }
}
